name: Esegui script Python

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC every day
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configura Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Installa le dipendenze
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager  # Aggiungi per gestire il ChromeDriver

      # Step 4: Installa Xvfb per il supporto headless
      - name: Installa Xvfb
        run: sudo apt-get install -y xvfb

      # Step 5: Esegui lo script Python
      - name: Esegui lo script
        env:
          PEPOGIT_TOKEN: ${{ secrets.PEPOGIT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          Xvfb :99 &    # Avvia Xvfb in background per simulare un display
          export DISPLAY=:99
          python req.py  # Esegui lo script Python con il display virtuale

